### ISSUE TITLE
Searching the ckan protocol rejects yields CkanApiError

### ISSUE THREAD

**Issue by allthesignals** [okfn/dpm#32]
http://dpm.readthedocs.org/en/latest/manual.html#obtaining-a-package

```
dpm search ckan:// iso --debug
DEBUG:dpm.index:dpm: CKAN config: {'base_location': 'http://thedatahub.org/api', 'api_key': ''}
Error: Got redirected to another URL, which does not work with POSTS. Redirection: http://thedatahub.org/api/search/package -> http://datahub.io/api/search/package

[** For (lots) more information run with --debug **]
DEBUG:dpm.cli:Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/dpm-0.10-py2.7.egg/dpm/cli/base.py", line 172, in main
    self.run(options, args)
  File "/Library/Python/2.7/site-packages/dpm-0.10-py2.7.egg/dpm/cli/standard.py", line 90, in run
    for pkg in index.search(query):
  File "/Library/Python/2.7/site-packages/dpm-0.10-py2.7.egg/dpm/index/ckan.py", line 51, in search
    for pkg_name in self.ckan.package_search(query)['results']:
  File "/Library/Python/2.7/site-packages/ckanclient-0.10-py2.7.egg/ckanclient/__init__.py", line 417, in package_search
    self.open_url(url, data, headers)
  File "/Library/Python/2.7/site-packages/ckanclient-0.10-py2.7.egg/ckanclient/__init__.py", line 233, in open_url
    raise CkanApiError(self.last_message)
CkanApiError: Got redirected to another URL, which does not work with POSTS. Redirection: http://thedatahub.org/api/search/package -> http://datahub.io/api/search/package
```

**Comment by rgrp** [comment]
Ahhhh. the dpm docs on readthedocs are for https://github.com/okfn/dpm-old - I think we should take them down. For the docs for current dpm please see the README

**Comment by rgrp** [comment]
FIXED. Have removed the old docs. Sorry for the confusion and please see the latest docs in the README.
